package com.raiwesy.ai.ui.theme

import androidx.compose.ui.graphics.Color

// Brand color (indigo)
val RaiwesyIndigo = Color(0xFF5B4FE9)

// ---------------------------------------------------------------------------
// Light color scheme (Material 3, indigo)
// ---------------------------------------------------------------------------
val md_light_primary = Color(0xFF4C46E0)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFE1DFFF)
val md_light_onPrimaryContainer = Color(0xFF191161)
val md_light_secondary = Color(0xFF5B5C71)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFE0E0F9)
val md_light_onSecondaryContainer = Color(0xFF18192B)
val md_light_tertiary = Color(0xFF77534E)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFFFDAD3)
val md_light_onTertiaryContainer = Color(0xFF2C1511)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFCF9FF)
val md_light_onBackground = Color(0xFF1B1B21)
val md_light_surface = Color(0xFFFCF9FF)
val md_light_onSurface = Color(0xFF1B1B21)
val md_light_surfaceVariant = Color(0xFFE4E1EC)
val md_light_onSurfaceVariant = Color(0xFF46464F)
val md_light_outline = Color(0xFF767680)
val md_light_outlineVariant = Color(0xFFC7C5D2)
val md_light_inverseSurface = Color(0xFF2F3036)
val md_light_inverseOnSurface = Color(0xFFF2F0F7)
val md_light_inversePrimary = Color(0xFFC5C3FF)
val md_light_surfaceDim = Color(0xFFDBD9E0)
val md_light_surfaceBright = Color(0xFFFCF9FF)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow = Color(0xFFF7F4FB)
val md_light_surfaceContainer = Color(0xFFF1EEF7)
val md_light_surfaceContainerHigh = Color(0xFFEBE8F1)
val md_light_surfaceContainerHighest = Color(0xFFE5E3EA)

// ---------------------------------------------------------------------------
// Dark color scheme (Material 3, indigo)
// ---------------------------------------------------------------------------
val md_dark_primary = Color(0xFFC5C3FF)
val md_dark_onPrimary = Color(0xFF221E68)
val md_dark_primaryContainer = Color(0xFF38329E)
val md_dark_onPrimaryContainer = Color(0xFFE1DFFF)
val md_dark_secondary = Color(0xFFC3C3DA)
val md_dark_onSecondary = Color(0xFF2D2F42)
val md_dark_secondaryContainer = Color(0xFF434659)
val md_dark_onSecondaryContainer = Color(0xFFE0E1F9)
val md_dark_tertiary = Color(0xFFE7BDB6)
val md_dark_onTertiary = Color(0xFF492925)
val md_dark_tertiaryContainer = Color(0xFF653F3A)
val md_dark_onTertiaryContainer = Color(0xFFFFDAD3)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF131318)
val md_dark_onBackground = Color(0xFFE4E1E9)
val md_dark_surface = Color(0xFF131318)
val md_dark_onSurface = Color(0xFFE4E1E9)
val md_dark_surfaceVariant = Color(0xFF46464F)
val md_dark_onSurfaceVariant = Color(0xFFC7C5D2)
val md_dark_outline = Color(0xFF91909B)
val md_dark_outlineVariant = Color(0xFF46464F)
val md_dark_inverseSurface = Color(0xFFE4E1E9)
val md_dark_inverseOnSurface = Color(0xFF2F3036)
val md_dark_inversePrimary = Color(0xFF4C46E0)
val md_dark_surfaceDim = Color(0xFF131318)
val md_dark_surfaceBright = Color(0xFF3A3A41)
val md_dark_surfaceContainerLowest = Color(0xFF0E0E13)
val md_dark_surfaceContainerLow = Color(0xFF1B1B21)
val md_dark_surfaceContainer = Color(0xFF1F1F25)
val md_dark_surfaceContainerHigh = Color(0xFF23222A)
val md_dark_surfaceContainerHighest = Color(0xFF2E2D35)
